#ifndef CARDREADERDONSEE_GLOBAL_H
#define CARDREADERDONSEE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CARDREADERDONSEE_LIBRARY)
#  define CARDREADERDONSEE_EXPORT Q_DECL_EXPORT
#else
#  define CARDREADERDONSEE_EXPORT Q_DECL_IMPORT
#endif

#endif // CARDREADERDONSEE_GLOBAL_H
